### ISSUE TITLE
Couldn't install pip packages in llm-server

### ISSUE THREAD

**Issue by harisankar01** [Quantum-Tutors/quantum-tutor#11]
1. Add python version in ReadMe of `llm-server`
2. Cross verify the pip packages
3. Add instructions to run the server

**Error**:

```
ERROR: Could not find a version that satisfies the requirement apparmor==3.1.7 (from versions: none)
ERROR: No matching distribution found for apparmor==3.1.7
```

**Env**:

Python 3.12.4
pip 24.0

**Comment by Namasivaayam-L** [comment]
I haven't pushed the updated requirement file da ..  so once I do that we won't have this issue.. for  now skip... setting up llm-server part.
